version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: biblioteca-sqlserver
    environment:
      SA_PASSWORD: "BibliotecaFort3!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./banco_de_dados/init-biblioteca.sql:/docker-entrypoint-initdb.d/init-biblioteca.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P BibliotecaFort3! -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sqlserver_data: